# Generated by Django 4.2.7 on 2023-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
